### ISSUE TITLE
Compatibility/Dependency with Newtonsoft's latest version

### ISSUE THREAD

**Issue by mjg-ott** [Twitterizer/Twitterizer#34] opened 2012-10-25 17:34 UTC
First off, LOVE Twitterizer...
That being said, I need access to other libraries (Twilio in particular) that are dependent upon Newtonsoft v4.5.10. 

Will you be updating Twitterizer or modifying the Nuget package to support this or are their compatibility issues in newer Newtonsoft component that will prevent this from working?

Kinda new to the whole Nuget thing and I must say, it doesn't appear to make things easier...

**Comment by DigitallyBorn** [comment] 2012-11-03 21:28
The source code in the develop branch has had corrections made to address this issue. Please provide some feedback about the code in the develop branch and I will push it to master and release an update to nuget.

**Comment by mjg-ott** [comment] 2012-11-05 16:00
Um... Ok. I'm new to the whole Git thing so I'll do my best to figure that
out.

In the meantime, I went ahead and recompiled locally and installed into my
project manually.

**Comment by jamiehowarth0** [comment] 2014-01-21 16:49
Related to/duplicate of #39, so closing.

**Closed as completed by jamiehowarth0** 2014-01-21 16:49 UTC
